### ISSUE TITLE
ISO 19115 - DCAT - Schema.org mapping

### ISSUE THREAD

**Issue by pieterprovoost** [iodepo/odis-arch#1]
https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.org_mapping

**Comment by skybristol** [comment]
Not sure what this issue is pointed toward. A bit of a description would be helpful.

We may find the [science-on-schema-org](https://github.com/ESIPFed/science-on-schema.org) work useful. Successful implementation of these methods really comes down to the semantics and use of accepted and useful community registries for identifiers. Otherwise, each implementation is its own island that has to be mapped and navigated.
