### ISSUE TITLE
[ODINAFRICA] connect the upcomingExpeditions database with ODIS

### ISSUE THREAD

**Issue by jmckenna** [iodepo/odis-arch#151]
- placeholder for new pattern development
- cc @dilianadineva @fils

**Comment by dilianadineva** [comment]
`research_expedition_id
vessel_id
vessel_type
vessel_dimensions
vessel_equipment
expedition_name
exp_description
expedition_code?
country_id
institution_affiliation?
cruise_contact_personnel
chief_scientist
start_date
end_date
cruise_track
website_link
linked_projects
collab_opportunities
ocean_region

{
    "@context": {
      "@vocab": "https://schema.org/"
    },
    "@type": "ResearchProject",
    "@id": "https://ioc-africa.org/test/ipcomingResearchExpeditions.php?id=1",
    "url": "website_link",
    "subjectOf": 
      {
        "@type": "Vehicle",
        "@id": "https://ioc-africa.org/test2/researchVessels.php?id=1",
        "name": "Link to vessel involved in this exp, could use @id if proper here, or just url",
        "url": "https://ioc-africa.org/test2/researchVessels.php?id=1",
        "vessel_type": "vessel_type",//bodyType?
        "size": "vessel_dimensions",
        "vessel_equipment": "vessel_equipment"//?"additionalProperty": {"vessel_equipment": []}
      },

    "name": "expedition_name",
    "description": "exp_description",
    "expedition_code": "expedition_code",//?
    "location": "country_id",
    "institution_affiliation": "institution_affiliation",//memberOf?
    "contactPoint": {
		"@type": "ContactPoint",
		"name": "cruise_contact_personnel"
	},
    "member": {
        "@type": "Person",
        "jobTitle": "chief scientist",
        "name": "chief_scientist"
      },
      "additionalProperty": [
        {
          "@type": "PropertyValue",
          "name": "Research Period",
          "description": "expedition_name",
          "startDate": "start_date",
          "endDate": "end_date"
        }
      ],
      "cruise_track": "cruise_track",//?
      "linked_projects": "linked_projects",//?
      "collab_opportunities": "collab_opportunities",//?
    "spatialCoverage": 
      {
        "@type": "Place",
        "@id": "https://marineregions.org/gazetteer.php?p=details&id=8566", // use one from https://marineregions.org/gazetteer.php?p=browser&id%5B%5D=29035&id%5B%5D=28833#focus
        "name": "ocean_region"
      },
    "keywords": []

**Comment by pbuttigieg** [comment]
xref #156

**Comment by pbuttigieg** [comment]
Some initial feedback:

* Rather than a project, this sounds like an schema:Event, scheduled for some future point in time.
* The potentialAction (xref #156) property and semantics might be appropriate here, as this makes it clear things are proposed rather than certain. 
* the subjectOf usage is not correct - it seems we want to express that a future Event has a Vehicle as a participant. We can do this via an additionalProperty linked to[ RO:'has participant'](http://purl.obolibrary.org/obo/RO_0000057 ), as I don't see a schema.org term that can do the same.
* "vessel_equipment" and others like it may indeed have to be additionalProperties, but schema:'[vehicleConfiguration](https://schema.org/vehicleConfiguration)' could work here too.
* ` "location": "country_id"` doesn't seem right / useful - many expeditions cross many nations or are in international waters. This should likely be a geospatial value (e.g. a line, polygon, etc)
* `"institution_affiliation": "institution_affiliation",//memberOf?` memberOf wouldn't work here, but maybe schema:organizer or schema:sponsor from schema:Event could 
* `"member"` may have to be subsituted with schema:contributor for semantic regularity
*  `"cruise_track"` for the cruise Event could be covered by spatialCoverage

We note that you're using attribute names from your database as values for keys, e.g.: 
>         "vessel_type": "vessel_type",//bodyType?
>          "size": "vessel_dimensions",
 
Note that these will be removed in the final template, substituted with more generic values.

**Comment by dilianadineva** [comment]
Made some changes - changed member to contributor, memberOf to organizer, commented out country_id for now, will remove it if not needed at all, added vehicle_name to additionalProperty, cruise_track to spatialCoverage, added vehicle_name to additionalProperty but unsure about the structure and how to link it to 'has participant' (and for the rest).  Saw an example in book.oceaninfohub for potentialAction having is a "instrument" property - any idea if we can use it for "vessel_equipment"? 
[(https://book.oceaninfohub.org/thematics/dataset/index.html)]
Here is a github link to the upcoming expeditions json-ld file:
[(https://github.com/dilianadineva/ODINAFRICA-Oean-Projects-JSON-LD-data-structure/blob/main/upcoming_expeditions_jsonld.json)]
