### ISSUE TITLE
documentation theme

### ISSUE THREAD

**Issue by pieterprovoost** [iodepo/odis-arch#21]
I suggest to use a Jekyll theme that's a bit more suitable for documentation, hosted on GitHub Pages or somewhere else. For example:

- https://pmarsceill.github.io/just-the-docs/
- https://dox.themejack.com/

**Comment by fils** [comment]
@pieterprovoost I assume this issue isn't relevant anymore since we went with jupyterbook?

Sadly, theme-ing is Jupyter Book is in the future.  So i hope everyone is OK with the look.  

I also find Jupyter Book's approach to multi-language to be lacking.  If I understand it correctly we can make it work, but it's not as easy as I would like.

**Comment by pieterprovoost** [comment]
Agreed, closing this issue.
